### ISSUE TITLE
add some hint about the submoule

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/drawio-intellij-plugin#12]
when cloned without the git submodule, the build will run into errors.
We should add a hint that - in this case - you have to execute
`git submodule update --init`
to fix this situation.

**Comment by hediet** [comment]
Thanks! It is fine for me like this, but maybe it should be communicated more proactively.
Like so:
```
== Build Instructions
* Run `git submodule update --init`
* Run `./gradlew runIde`
```

**Comment by rdmueller** [comment]
many tools already clone with submodules, so the init might not be needed.
maybe we should add a task which checks for the submodule and inits it if necessary. This would make it completly transparent.
