### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by hediet** [docToolchain/drawio-intellij-plugin#13]
I think [these workflows](https://github.com/JetBrains/intellij-platform-plugin-template/tree/main/.github/workflows) can just be copied over.

**Comment by rdmueller** [comment]
see https://github.com/rdmueller/drawio-intellij-plugin/tree/actions/.github/workflows for WIP

**Comment by rdmueller** [comment]
build works: https://github.com/rdmueller/drawio-intellij-plugin/actions/runs/354434979
