### ISSUE TITLE
Support *.drawio.png

### ISSUE THREAD

**Issue by hediet** [docToolchain/drawio-intellij-plugin#15]
The MVP only allows to load xml like diagrams (like *.drawio and *.drawio.svg files).
Regardless of the input, the diagram is saved as drawio xml.

It would be nice if diagrams would be saved as png if the file has a .drawio.png/.dio.png extension.

To implement this, don't just directly save the xml property. Rather, check the file extension of the virtual file and use the export action to convert the file (on every autosave).

**Comment by rdmueller** [comment]
In addition, I think we have to extract the meta data from the `.png` file in order to load the diagram.

**Comment by hediet** [comment]
No we don't. You can send the png content base64 encoded. Look at how I did it in the vscode extension!

**Comment by rdmueller** [comment]
thanx. so the base64 encoding does the trick. this makes it a lot easier!

**Comment by rdmueller** [comment]
see #23
