### ISSUE TITLE
Support *.drawio.svg

### ISSUE THREAD

**Issue by hediet** [docToolchain/drawio-intellij-plugin#5]
The MVP only allows to load xml like diagrams (like *.drawio and *.drawio.svg files).
Regardless of the input, the diagram is saved as drawio xml.

It would be nice if diagrams would be saved as svg if the file has a *.drawio.svg/*.dio.svg extension.

To implement this, don't just directly save the xml property. Rather, check the file extension of the virtual file and use the export action to convert the file (on every autosave).

**Comment by rdmueller** [comment]
#14 implements support for `*.drawio.svg`

**Comment by rdmueller** [comment]
I guess we can close this now.
